# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Armadillo-based reimplementation of `stats::quantile()` for `type=7`.
#' @description Allows for NAs.
#' @param x a vec of values for which to find the quantiles
#' @param probs a vec of probilities that specify which quantiles 
#' @returns a vec of quantiles
#' @examples
#' set.seed(12345)
#' y <- rnorm(1e5)
#' # Should be near zero for all quantiles
#' quantile(y) - quantile_type7(y, seq(0, 1, length.out = 5))
#' quantile(y, 0.975) - quantile_type7(y, 0.975)
#' # NA probs are allowed (unlike base quantile()):
#' quantile_type7(y, probs = c(0.1, 0.5, 1, 2, 5, 10, 50, NA) / 100)
#' @export
quantile_type7 <- function(x, probs) {
    .Call(`_genhaz_quantile_type7`, x, probs)
}

#' C++ reimplementation of survPen::crs, including derivatives.
#' @description The re-implementation uses the same algorithm but uses
#' different defaults, and allows for derivatives.
#' For the changes in defaults: the function here assumes that
#' the intercept is false (as per `splines::ns`); when the knots are
#' not specified, the function defaults to using `x` rather than `unique(x)`
#' for the quantiles; and the `df` argument comes before the `knots` argument.
#' To use the `survPen::crs` defaults in R, use
#' `crs_cpp(..., intercept=TRUE, survPen_compatible=TRUE)`.
#' @param x a vec of values to provide
#' @param df a non-negative integer for the degrees of freedom (ignored if
#' the knots are specified)
#' @param knots a vec of knots (defaults to NULL)
#' @param derivs a non-negative integer for the derivative (default 0)
#' @param intercept a bool for whether to include the intercept
#' @param survPen_compatible a bool for whether to use `unique(x)` for determining the knots if the `knots` are not specified 
#' @return an `Rcpp::NumericMatrix` with attributes `class="crs_cpp"`,
#' `pen` for the penalty matrix, `knots` for the knots, `derivs` for the order of
#' derivatives, and `intercept` for a bool/logical for whether the intercept is
#' included.
#' @examples
#' x     <- seq(0, 1, length.out = 11)
#' knots <- c(1, 3, 5, 7) / 10
#' crs1  <- crs_cpp(x, knots = knots)
#' dim(crs1)
#' # Comparison with survPen::crs requires the survPen package:
#' \dontrun{
#' library(survPen)
#' crs2 <- crs(x, knots, intercept = FALSE)
#' range(crs1 - crs2$bs)
#' range(attr(crs1, "pen") - crs2$pen)
#' }
#' @export
crs_cpp <- function(x, df = 10L, knots = NULL, derivs = 0L, intercept = FALSE, survPen_compatible = FALSE) {
    .Call(`_genhaz_crs_cpp`, x, df, knots, derivs, intercept, survPen_compatible)
}

#' C++ reimplementation of `smf`, including derivatives.
#' @description The re-implementation uses the same algorithm but uses
#' different defaults. Note that the inclusion of an
#' intercept is the same as `crs_cpp`, while no intercept uses a projection
#' based on a QR decomposition.
#' For the changes in defaults: the function here assumes that
#' the intercept is false (as per `splines::ns`); and when the knots are
#' not specified, the function defaults to using `x` rather than `unique(x)`
#' for the quantiles. The `survPen` implementation for `smf` assumes no
#' intercept unless there is a `by` variable. A `by` variable `x2` would
#' be implemented here by an interaction, such as
#' `smf_cpp(x,knots,intercept=TRUE):x2`; see the examples. 
#' @param x a vec of values to provide
#' @param df a non-negative integer for the degrees of freedom (ignored if
#' the knots are specified)
#' @param knots a vec of knots (defaults to NULL)
#' @param derivs a non-negative integer for the derivative (default 0)
#' @param intercept a bool for whether to include the intercept
#' @param Z optional pre-computed QR projection matrix (arma::mat). If
#'   provided, overrides the internally computed centering matrix.
#' @param survPen_compatible a bool for whether to use `unique(x)` for
#' determining the knots if the `knots` are not specified
#' @return an `Rcpp::NumericMatrix` with attributes `class="smf_cpp"`,
#' `pen` for the penalty matrix, `knots` for the knots, `derivs` for the order of
#' derivatives, and `intercept` for a bool/logical for whether the intercept is
#' included. If there is no intercept, then there will also be a `Z` attribute
#' which is the QR-based projection matrix.
#' @examples
#' x     <- seq(0, 1, length.out = 11)
#' knots <- c(1, 3, 5, 7) / 10
#' smf1  <- smf_cpp(x, knots = knots)
#' dim(smf1)
#' # Check that Z attribute is available without intercept:
#' !is.null(attr(smf1, "Z"))
#'
#' ## Derivative check via finite differences (knots must be explicit)
#' smfD <- function(t, knots, eps = 1e-5) {
#'   (smf_cpp(t + eps, knots = knots) - smf_cpp(t - eps, knots = knots)) / (2 * eps)
#' }
#' x2 <- seq(0, 1, length.out = 101)
#' max(abs(smf_cpp(x2, knots = knots, derivs = 1) - smfD(x2, knots = knots)))
#'
#' ## Comparison with survPen::smooth.cons (requires survPen):
#' \dontrun{
#' library(survPen)
#' smf2 <- smooth.cons("x", knots = list(knots), df = 4, option = "smf",
#'                     data.spec = data.frame(x = x), name = "smf(time)")
#' range(smf1 - smf2$X)
#' range(attr(smf1, "pen") - smf2$pen[[1]])
#' }
#' @export
smf_cpp <- function(x, df = 10L, knots = NULL, intercept = FALSE, derivs = 0L, Z = NULL, survPen_compatible = FALSE) {
    .Call(`_genhaz_smf_cpp`, x, df, knots, intercept, derivs, Z, survPen_compatible)
}

