// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// quantile_type7
arma::vec quantile_type7(arma::vec x, arma::vec probs);
RcppExport SEXP _genhaz_quantile_type7(SEXP xSEXP, SEXP probsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type probs(probsSEXP);
    rcpp_result_gen = Rcpp::wrap(quantile_type7(x, probs));
    return rcpp_result_gen;
END_RCPP
}
// crs_cpp
Rcpp::NumericMatrix crs_cpp(arma::vec x, size_t df, Rcpp::Nullable<arma::vec> knots, size_t derivs, bool intercept, bool survPen_compatible);
RcppExport SEXP _genhaz_crs_cpp(SEXP xSEXP, SEXP dfSEXP, SEXP knotsSEXP, SEXP derivsSEXP, SEXP interceptSEXP, SEXP survPen_compatibleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    Rcpp::traits::input_parameter< size_t >::type df(dfSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<arma::vec> >::type knots(knotsSEXP);
    Rcpp::traits::input_parameter< size_t >::type derivs(derivsSEXP);
    Rcpp::traits::input_parameter< bool >::type intercept(interceptSEXP);
    Rcpp::traits::input_parameter< bool >::type survPen_compatible(survPen_compatibleSEXP);
    rcpp_result_gen = Rcpp::wrap(crs_cpp(x, df, knots, derivs, intercept, survPen_compatible));
    return rcpp_result_gen;
END_RCPP
}
// smf_cpp
Rcpp::NumericMatrix smf_cpp(arma::vec x, size_t df, Rcpp::Nullable<arma::vec> knots, bool intercept, size_t derivs, Rcpp::Nullable<arma::mat> Z, bool survPen_compatible);
RcppExport SEXP _genhaz_smf_cpp(SEXP xSEXP, SEXP dfSEXP, SEXP knotsSEXP, SEXP interceptSEXP, SEXP derivsSEXP, SEXP ZSEXP, SEXP survPen_compatibleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    Rcpp::traits::input_parameter< size_t >::type df(dfSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<arma::vec> >::type knots(knotsSEXP);
    Rcpp::traits::input_parameter< bool >::type intercept(interceptSEXP);
    Rcpp::traits::input_parameter< size_t >::type derivs(derivsSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<arma::mat> >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< bool >::type survPen_compatible(survPen_compatibleSEXP);
    rcpp_result_gen = Rcpp::wrap(smf_cpp(x, df, knots, intercept, derivs, Z, survPen_compatible));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_genhaz_quantile_type7", (DL_FUNC) &_genhaz_quantile_type7, 2},
    {"_genhaz_crs_cpp", (DL_FUNC) &_genhaz_crs_cpp, 6},
    {"_genhaz_smf_cpp", (DL_FUNC) &_genhaz_smf_cpp, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_genhaz(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
